services:
  wire-pod:
    hostname: escapepod
    build: .
    network_mode: host # b/c mDNS escapepod.local broadcast... why use mDNS? people hosting a custom vector "server" are clearly capable of setting up a DNS record...
    platform: linux/arm64
    image: ghcr.io/kercre123/wire-pod:main
    restart: unless-stopped
    ports:
      - 443:443
      - 8080:8080
      - 80:80
      - 8084:8084
    volumes:
      - wire-pod-data:/chipper/
      - wire-pod-model:/vosk/
volumes:
  wire-pod-data:
    driver: local
  wire-pod-model:
    driver: local
